package traffic

import "github.com/intersight/intersight-go"

const (
	ChannelSearchOrganic  intersight.TrafficChannel = "search.organic"
	ChannelSearchPaid     intersight.TrafficChannel = "search.paid"
	ChannelSocialMedia    intersight.TrafficChannel = "social"
	ChannelEmailMarketing intersight.TrafficChannel = "email"
	ChannelDirect         intersight.TrafficChannel = "direct"
	ChannelAffiliate      intersight.TrafficChannel = "affiliate"
	ChannelContent        intersight.TrafficChannel = "content"
	ChannelRetargetting   intersight.TrafficChannel = "retargetting"
	ChannelOffline        intersight.TrafficChannel = "offline"
	ChannelPrint          intersight.TrafficChannel = "print"
	ChannelPhone          intersight.TrafficChannel = "phone"
	ChannelPartners       intersight.TrafficChannel = "partners"
	ChannelIntegration    intersight.TrafficChannel = "integration"
	ChannelWordOfMouth    intersight.TrafficChannel = "wordofmouth"

	SubChannelEmailNewsletter    = "newsletter"
	SubChannelEmailCourse        = "course"
	SubChannelEmailMailShot      = "mailshot"
	SubChannelContentBlog        = "blog"
	SubChannelContentGuestBlog   = "guestblog"
	SubChannelContentHowToGuide  = "howtoguide"
	SubChannelContentInfographic = "infographic"
	SubChannelContentVideo       = "video"
	SubChannelContentTestimonial = "testimonial"
	SubChannelContentCaseStudy   = "casestudy"
	SubChannelContentWhitePaper  = "whitepaper"
	SubChannelContentMeme        = "meme"
	SubChannelContentEBook       = "ebook"
	SubChannelContentPodCast     = "podcast"
	SubChannelContentNewsJacking = "newsjacking"
	SubChannelOfflineTV          = "tv"
	SubChannelOfflineRadio       = "radio"
	SubChannelOfflineBillboard   = "billboard"
	SubChannelPrintNewspaper     = "newspaper"
	SubChannelPrintNewsletter    = "newsletter"
	SubChannelPrintFlyer         = "flyer"
	SubChannelPrintMagazine      = "magazine"
	SubChannelPhoneColdCall      = "cold"
	SubChannelPhoneInbound       = "inbound"
)
