package traffic

import (
	"github.com/intersights/intersights-go"
)

const (
	ChannelSearchOrganic  intersights.TrafficChannel = "search.organic"
	ChannelSearchPaid     intersights.TrafficChannel = "search.paid"
	ChannelSocialMedia    intersights.TrafficChannel = "social"
	ChannelEmailMarketing intersights.TrafficChannel = "email"
	ChannelDirect         intersights.TrafficChannel = "direct"
	ChannelAffiliate      intersights.TrafficChannel = "affiliate"
	ChannelContent        intersights.TrafficChannel = "content"
	ChannelReTarget       intersights.TrafficChannel = "retarget"
	ChannelOffline        intersights.TrafficChannel = "offline"
	ChannelPrint          intersights.TrafficChannel = "print"
	ChannelPhone          intersights.TrafficChannel = "phone"
	ChannelPartners       intersights.TrafficChannel = "partners"
	ChannelIntegration    intersights.TrafficChannel = "integration"
	ChannelWordOfMouth    intersights.TrafficChannel = "wordofmouth"

	SubChannelEmailNewsletter    = "newsletter"
	SubChannelEmailCourse        = "course"
	SubChannelEmailMailShot      = "mailshot"
	SubChannelContentBlog        = "blog"
	SubChannelContentGuestBlog   = "guestblog"
	SubChannelContentHowToGuide  = "howtoguide"
	SubChannelContentInfographic = "infographic"
	SubChannelContentVideo       = "video"
	SubChannelContentTestimonial = "testimonial"
	SubChannelContentCaseStudy   = "casestudy"
	SubChannelContentWhitePaper  = "whitepaper"
	SubChannelContentMeme        = "meme"
	SubChannelContentEBook       = "ebook"
	SubChannelContentPodCast     = "podcast"
	SubChannelContentNewsJacking = "newsjacking"
	SubChannelOfflineTV          = "tv"
	SubChannelOfflineRadio       = "radio"
	SubChannelOfflineBillboard   = "billboard"
	SubChannelPrintNewspaper     = "newspaper"
	SubChannelPrintNewsletter    = "newsletter"
	SubChannelPrintFlyer         = "flyer"
	SubChannelPrintMagazine      = "magazine"
	SubChannelPhoneColdCall      = "cold"
	SubChannelPhoneInbound       = "inbound"
)
